services:
  - type: web
    name: portfolio
    env: static
    staticPublishPath: .
    buildCommand: ""
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600
      - path: /*.js
        name: Cache-Control
        value: public, max-age=31536000
      - path: /*.pdf
        name: Cache-Control
        value: public, max-age=31536000
